# Generated by Django 3.2.24 on 2024-02-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count_products',
            field=models.IntegerField(default=0),
        ),
    ]
