# Generated by Django 3.2.24 on 2024-02-22 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(blank=True, unique=True, verbose_name='Size for the product(grams)')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sku', to='products.product')),
            ],
            options={
                'verbose_name': 'Stpre Keeping Unit',
                'verbose_name_plural': 'Store Keeping Units',
                'db_table': 'sku',
                'ordering': [],
            },
        ),
    ]
