# Generated by Django 3.2.24 on 2024-02-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_price_from_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Price payable by customer (Rs.)', null=True, verbose_name='selling price (Rs.)'),
        ),
    ]
