# Generated by Django 3.2.24 on 2024-02-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_price_in_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, help_text='Price payable by customer (Rs.)', verbose_name='selling price (Rs.)'),
        ),
    ]
