# Generated by Django 3.2.24 on 2024-02-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20240222_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='price',
            new_name='selling_price',
        ),
        migrations.AddField(
            model_name='sku',
            name='cost_price',
            field=models.PositiveSmallIntegerField(default=0, help_text='Cost Price of the product (Rs.)', verbose_name='Cost price (Rs.)'),
        ),
        migrations.AddField(
            model_name='sku',
            name='platform_commission',
            field=models.PositiveSmallIntegerField(default=0, help_text='Price incurred on the platform (Rs.)', verbose_name='Platform price (Rs.)'),
        ),
    ]
